on:
  pull_request:

jobs:
  slack_notif:
    if: startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack
        run: |
          curl -L -H "Accept: application/json" ${{ secrets.SLACK_DEPENDABOT_HOOK }} -d '{"pr_url":"${{ github.event.pull_request.html_url }}", "repo_name":"${{ github.repository }}", "pr_title":"${{ github.event.pull_request.title }}", "dependabot_url":"https://github.com/${{ github.repository }}/security/dependabot"}'
